security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /blog/admin
                login_path: /blog/admin/login
                check_path:  fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: vostre_blog_homepage
            #logout:       true
            anonymous:    true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/blog/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/blog/admin/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/blog/admin/.*, role: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/?, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
