<?php

namespace Vostre\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    
    public function listarTodasPorPost($post){
        $qb = $this->createQueryBuilder('t')
                ->select('t.id', 't.tag')
                ->distinct()
                ->where('t.post = :post')
                ->addOrderBy('t.tag', 'ASC')
                ->setParameter('post', $post);
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function deletarTodasPorPost($post){
        $qb = $this->createQueryBuilder('t')
                ->delete('VostreBlogBundle:Tag','t')
                ->where('t.post = :post')
                ->setParameter('post', $post);
        
        return $qb->getQuery()->getResult();
        
    }
    
}
